//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nexosale30.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string Button_AboutToClose {
            get {
                return ResourceManager.GetString("Button.AboutToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Button_CancelX {
            get {
                return ResourceManager.GetString("Button.CancelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Button_CloseX {
            get {
                return ResourceManager.GetString("Button.CloseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_green {
            get {
                object obj = ResourceManager.GetObject("button_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_red {
            get {
                object obj = ResourceManager.GetObject("button_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declined.
        /// </summary>
        internal static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send.
        /// </summary>
        internal static string FailedToSend {
            get {
                return ResourceManager.GetString("FailedToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sur you want to cancel the operation ?.
        /// </summary>
        internal static string FConfirm_CancelOperationRequest {
            get {
                return ResourceManager.GetString("FConfirm.CancelOperationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter today&apos;s date (YYYYMMDD):.
        /// </summary>
        internal static string FConfirm_EnterTodaysDate {
            get {
                return ResourceManager.GetString("FConfirm.EnterTodaysDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid admin code.
        /// </summary>
        internal static string FConfirm_InvalidAdminCode {
            get {
                return ResourceManager.GetString("FConfirm.InvalidAdminCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER RECEIPT.
        /// </summary>
        internal static string FPrint_CustomerReceipt {
            get {
                return ResourceManager.GetString("FPrint.CustomerReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERCHANT RECEIPT.
        /// </summary>
        internal static string FPrint_MerchantReceipt {
            get {
                return ResourceManager.GetString("FPrint.MerchantReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting transaction.
        /// </summary>
        internal static string FProcessing_AbortInProgress {
            get {
                return ResourceManager.GetString("FProcessing.AbortInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT REQUEST.
        /// </summary>
        internal static string FProcessing_AbortRequest {
            get {
                return ResourceManager.GetString("FProcessing.AbortRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No amount.
        /// </summary>
        internal static string FProcessing_Amount {
            get {
                return ResourceManager.GetString("FProcessing.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, transaction processing could not complete.
        /// </summary>
        internal static string FProcessing_AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("FProcessing.AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICALLY CLOSING WINDOW.
        /// </summary>
        internal static string FProcessing_AutomaticallyClosingWindow {
            get {
                return ResourceManager.GetString("FProcessing.AutomaticallyClosingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELLED BY USER.
        /// </summary>
        internal static string FProcessing_CancelledByUser {
            get {
                return ResourceManager.GetString("FProcessing.CancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to POI.
        /// </summary>
        internal static string FProcessing_FailedToConnectToPOI {
            get {
                return ResourceManager.GetString("FProcessing.FailedToConnectToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        internal static string FProcessing_FROM {
            get {
                return ResourceManager.GetString("FProcessing.FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CANCELLATION processing.
        /// </summary>
        internal static string FProcessing_InvalidCancellationProcessing {
            get {
                return ResourceManager.GetString("FProcessing.InvalidCancellationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PAYMENT processing.
        /// </summary>
        internal static string FProcessing_InvalidPaymentProcessing {
            get {
                return ResourceManager.GetString("FProcessing.InvalidPaymentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RECONCILIATION processing.
        /// </summary>
        internal static string FProcessing_InvalidReconciliationProcessing {
            get {
                return ResourceManager.GetString("FProcessing.InvalidReconciliationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN SALE.
        /// </summary>
        internal static string FProcessing_LoginSale {
            get {
                return ResourceManager.GetString("FProcessing.LoginSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to POI.
        /// </summary>
        internal static string FProcessing_LoginToPOI {
            get {
                return ResourceManager.GetString("FProcessing.LoginToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from POI.
        /// </summary>
        internal static string FProcessing_LogoutFromPOI {
            get {
                return ResourceManager.GetString("FProcessing.LogoutFromPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT SALE.
        /// </summary>
        internal static string FProcessing_LogoutSale {
            get {
                return ResourceManager.GetString("FProcessing.LogoutSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory amount.
        /// </summary>
        internal static string FProcessing_MissingAmount {
            get {
                return ResourceManager.GetString("FProcessing.MissingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory currency.
        /// </summary>
        internal static string FProcessing_MissingCurrency {
            get {
                return ResourceManager.GetString("FProcessing.MissingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasn&apos;t been processed successfully.
        /// </summary>
        internal static string FProcessing_NotProcessedSuccessfully {
            get {
                return ResourceManager.GetString("FProcessing.NotProcessedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction to process.
        /// </summary>
        internal static string FProcessing_NoTxnToProcess {
            get {
                return ResourceManager.GetString("FProcessing.NoTxnToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO TRANSACTION TO PROCESS.
        /// </summary>
        internal static string FProcessing_NoTxnToProcessCaption {
            get {
                return ResourceManager.GetString("FProcessing.NoTxnToProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been cancelled.
        /// </summary>
        internal static string FProcessing_OperationCancelled {
            get {
                return ResourceManager.GetString("FProcessing.OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation timed out and has been cancelled.
        /// </summary>
        internal static string FProcessing_OperationTimedout {
            get {
                return ResourceManager.GetString("FProcessing.OperationTimedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation will not complete.
        /// </summary>
        internal static string FProcessing_OperationWontComplete {
            get {
                return ResourceManager.GetString("FProcessing.OperationWontComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment in progress.
        /// </summary>
        internal static string FProcessing_PaymentInProgress {
            get {
                return ResourceManager.GetString("FProcessing.PaymentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT REQUEST.
        /// </summary>
        internal static string FProcessing_PaymentRequest {
            get {
                return ResourceManager.GetString("FProcessing.PaymentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please check your network connection.
        /// </summary>
        internal static string FProcessing_PleaseCheckNetwork {
            get {
                return ResourceManager.GetString("FProcessing.PleaseCheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing check.
        /// </summary>
        internal static string FProcessing_PrintCheckInProgress {
            get {
                return ResourceManager.GetString("FProcessing.PrintCheckInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT CHECK REQUEST.
        /// </summary>
        internal static string FProcessing_PrintCheckRequest {
            get {
                return ResourceManager.GetString("FProcessing.PrintCheckRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been processed successfully.
        /// </summary>
        internal static string FProcessing_ProcessedSuccessfully {
            get {
                return ResourceManager.GetString("FProcessing.ProcessedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading check.
        /// </summary>
        internal static string FProcessing_ReadCheckInProgress {
            get {
                return ResourceManager.GetString("FProcessing.ReadCheckInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ CHECK REQUEST.
        /// </summary>
        internal static string FProcessing_ReadCheckRequest {
            get {
                return ResourceManager.GetString("FProcessing.ReadCheckRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation in progress.
        /// </summary>
        internal static string FProcessing_ReconciliationInProgress {
            get {
                return ResourceManager.GetString("FProcessing.ReconciliationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECONCILIATION REQUEST.
        /// </summary>
        internal static string FProcessing_ReconciliationRequest {
            get {
                return ResourceManager.GetString("FProcessing.ReconciliationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund in progress.
        /// </summary>
        internal static string FProcessing_RefundInProgress {
            get {
                return ResourceManager.GetString("FProcessing.RefundInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUND REQUEST.
        /// </summary>
        internal static string FProcessing_RefundRequest {
            get {
                return ResourceManager.GetString("FProcessing.RefundRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling purchase.
        /// </summary>
        internal static string FProcessing_ReversalInProgress {
            get {
                return ResourceManager.GetString("FProcessing.ReversalInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVERSAL REQUEST.
        /// </summary>
        internal static string FProcessing_ReversalRequest {
            get {
                return ResourceManager.GetString("FProcessing.ReversalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale connected.
        /// </summary>
        internal static string FProcessing_SaleConnected {
            get {
                return ResourceManager.GetString("FProcessing.SaleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale deconnected.
        /// </summary>
        internal static string FProcessing_SaleDeconnected {
            get {
                return ResourceManager.GetString("FProcessing.SaleDeconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale failed to connect.
        /// </summary>
        internal static string FProcessing_SaleFailedToConnect {
            get {
                return ResourceManager.GetString("FProcessing.SaleFailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale failed to deconnect.
        /// </summary>
        internal static string FProcessing_SaleFailedToDeconnect {
            get {
                return ResourceManager.GetString("FProcessing.SaleFailedToDeconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMEOUT.
        /// </summary>
        internal static string FProcessing_TIMEOUT {
            get {
                return ResourceManager.GetString("FProcessing.TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        internal static string FProcessing_TO {
            get {
                return ResourceManager.GetString("FProcessing.TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction hasn&apos;t been reversed.
        /// </summary>
        internal static string FProcessing_TransactionNotReversed {
            get {
                return ResourceManager.GetString("FProcessing.TransactionNotReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been reversed.
        /// </summary>
        internal static string FProcessing_TransactionReversed {
            get {
                return ResourceManager.GetString("FProcessing.TransactionReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from sale.
        /// </summary>
        internal static string FromSale {
            get {
                return ResourceManager.GetString("FromSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM SALE.
        /// </summary>
        internal static string FromSaleU {
            get {
                return ResourceManager.GetString("FromSaleU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default printer).
        /// </summary>
        internal static string FSelectPrinter_DefaultPrinter {
            get {
                return ResourceManager.GetString("FSelectPrinter.DefaultPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXOSale settings.
        /// </summary>
        internal static string FSettings_Caption {
            get {
                return ResourceManager.GetString("FSettings.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files|*.png;*.jpg;*.jpeg;*.bmp|All files|*.*.
        /// </summary>
        internal static string FSettings_ImagesFiles {
            get {
                return ResourceManager.GetString("FSettings.ImagesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files|*.log|Text files|*.txt|All files|*.*.
        /// </summary>
        internal static string FSettings_LogsFiles {
            get {
                return ResourceManager.GetString("FSettings.LogsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printer selected.
        /// </summary>
        internal static string FSettings_NoPrinter {
            get {
                return ResourceManager.GetString("FSettings.NoPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file hasn&apos;t been saved. Please check file name and path.
        /// </summary>
        internal static string FSettings_SettingsFileNotSaved {
            get {
                return ResourceManager.GetString("FSettings.SettingsFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json files|*.json|Text files|*.txt|All files|*.*.
        /// </summary>
        internal static string FSettings_SettingsFiles {
            get {
                return ResourceManager.GetString("FSettings.SettingsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings have been modified.
        /// </summary>
        internal static string FSettings_SomeSettingsModified {
            get {
                return ResourceManager.GetString("FSettings.SomeSettingsModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save them ?.
        /// </summary>
        internal static string FSettings_SomeSettingsModifiedSaveThem {
            get {
                return ResourceManager.GetString("FSettings.SomeSettingsModifiedSaveThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image file is not supported or does not contain a valid image.
        /// </summary>
        internal static string FSettings_UnsupportedImageFile {
            get {
                return ResourceManager.GetString("FSettings.UnsupportedImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTING TO POI.
        /// </summary>
        internal static string FWait_ConnectingToPOI {
            get {
                return ResourceManager.GetString("FWait.ConnectingToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTING TO POI (USING BACKUP).
        /// </summary>
        internal static string FWait_ConnectingToPOIBackup {
            get {
                return ResourceManager.GetString("FWait.ConnectingToPOIBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTION FAILED, CHECK SETTINGS.
        /// </summary>
        internal static string FWait_ConnectionFailed {
            get {
                return ResourceManager.GetString("FWait.ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR STARTING CONNECTION PROCESS.
        /// </summary>
        internal static string FWait_ErrorStartingConnectionProcess {
            get {
                return ResourceManager.GetString("FWait.ErrorStartingConnectionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL ERROR CONNECTING TO PO.
        /// </summary>
        internal static string FWait_FatalError {
            get {
                return ResourceManager.GetString("FWait.FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string InWord {
            get {
                return ResourceManager.GetString("InWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI return code.
        /// </summary>
        internal static string NexoErrorInformation {
            get {
                return ResourceManager.GetString("NexoErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
    }
}
